In [1]:
# Importing numpy and assigning it to np
import numpy as np
#creating an array 
arr = np.array([1,3,4,5,6])
arr

array([1, 3, 4, 5, 6])

In [2]:
# finding the dimensions of an array
arr.shape

(5,)

In [3]:
# Finding the array type
arr.dtype

dtype('int32')

# Creating Arrays

In [4]:
# creating an array and defining its shape
arr = np.array([[1,2,3],[2,4,6],[8,8,8]])
arr.shape

(3, 3)

In [5]:
# Viewing the output of the array
arr

array([[1, 2, 3],
       [2, 4, 6],
       [8, 8, 8]])

In [7]:
# Creating a matrix of required dimensions containing only 0's
arr = np.zeros((2,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
# Creating a matrix of required dimensions containing only 1's
arr = np.ones((2,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
# Creating an identity matrix of required dimensions
arr = np.identity(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
#generating a matrix randomly
arr = np.random.randn(3,4)
arr

array([[ 0.7622228 , -0.86341633, -0.76758244,  0.5279775 ],
       [-0.94804541, -0.49093588, -1.08496893, -0.29298957],
       [-0.44312213, -2.21945534,  0.75366241,  1.44553425]])

In [14]:
# BytesIO is taken as input and a matrix is created  using delimiter (,) to separate values.
from io import BytesIO
b = BytesIO(b"2,23,33\n32,42,63.4\n35,77,12")
arr = np.genfromtxt(b, delimiter=",")
arr

array([[ 2. , 23. , 33. ],
       [32. , 42. , 63.4],
       [35. , 77. , 12. ]])

# Accessing the Array Elements
## Simple Indexing

In [15]:
# printing row from the above matrix.
arr[1]

array([32. , 42. , 63.4])

In [18]:
# creating 2 matrices of dimensions 2*3. Range is provided as 12
arr = np.arange(12).reshape(2,2,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [20]:
# Printing 1st matrix from above
arr[0]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
# Printing array and provided range is 10 starting from 5
arr = np.arange(10)
arr[5:]

array([5, 6, 7, 8, 9])

In [22]:
# From the above matrix print 5 to 8 (Upper limit is not printed. so one value extra must be provided.) 
arr[5:8]

array([5, 6, 7])

In [23]:
#from the parent array print all the values and upper limit is provded 
arr[:-5]

array([0, 1, 2, 3, 4])

In [24]:
arr = np.arange(12).reshape(2,2,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [25]:
# ptinting 2nd matrix from the created matrix 
arr[1:2]

array([[[ 6,  7,  8],
        [ 9, 10, 11]]])

In [31]:
arr = np.arange(27).reshape(3,3,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [32]:
# Printing values of column2 == column #3
arr[...,2]

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

In [33]:
# one more method
arr[...,2]

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

# Advance Indexing

In [34]:
#Integer array indexing
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [35]:
#the first part identifies the rows we want to access and the second identifies the columns which we want to address
arr[[0,1,2],[1,0,0]]

array([1, 3, 6])

# Boolean Indexing